baseURL = "https://yasserrabee.me"
# include content marked as draft
buildDrafts = false
# include content with publishdate in the future
buildFuture = false
# include content already expired
buildExpired = false
# enable this to make all relative URLs relative to content root. Note that this does not affect absolute URLs.
relativeURLs = true
disableRSS = true
enableRobotsTXT = true
editor = "nano"
languageCode = "en"
language = "en"
theme = "vncnt-hugo"
title = "Yasser Rabee - Software Engineer"

[permalinks]
  fixed = ":title/"
  posts = "posts/:slug/"

[params]
  author = "Yasser Rabee"
  email = "yasserrabee@gmail.co,"
  description = "Software Engineer"
  bio = ""
  avatar = "img/avatar.jpg"
  favicon = "img/favicon.ico"
  error404 = "There is no such page."

  [params.contact]
    github = "https://github.com/yasserrabee"
#    instagram = ""
#    twitter = ""
#    ello = ""
